name: GitHubActions

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone my repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v13.1

    - name: Find tabs in changed files
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          grep -P "\t" $file >> report.log 2>&1
        done

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        path: report.log
